### ISSUE TITLE
Printed coverage report is not the same as jacoco html report

### ISSUE THREAD

**Issue by amimas** [jansauer/gradle-print-coverage-plugin#3]
Hi,

I understand that this plugin relies on the xml report generated by jacoco and then prints them on the console. However, the coverage information that is printed in the console seems to be different from the html report generated by jacoco.

For example, when I look at the jacoco html report, the coverage on `INSTRUCTION` is 9% and on `BRANCH` is 5%. But this plugin prints both of them as 9.99% and 5.84% respectively.

Is this expected? Is the plugin rounding up the coverage info?

**Comment by amimas** [comment]
Is this project being maintained anymore?

**Comment by sroettering** [comment]
Yes it is still maintained. @jansauer is investigating this issue.

**Comment by amimas** [comment]
That's great!!

**Comment by jansauer** [comment]
@amimas Sorry that it took me that long but tis is only a free time project of mine.
I'm assuming that it is the other way around. Unfortunately the percentage values, displayed in the html report, are not part of the xml output. Instead the plugin is calculating it via the number of missed vs. the total lines of code.
https://github.com/jansauer/gradle-print-coverage-plugin/blob/7605f2f7366d760807a931e0e5324081b963f3db/src/main/groovy/de/jansauer/printcoverage/PrintCoverageTask.groovy#L34

Hope this answer is still helpful and if not please let me know.
